[Project]
Name = @projectName@
BuildgraphPath = Scripts\Build\BuildGraph\BuildGraph.xml
BuildgraphSharedProperties = Publish_Directory=Saved/LocalBuilds
AutomationScriptsDirectories = Scripts/Automation

[Jenkins]
; BuildgraphSharedStoragePath = \\nas\jenkins\UE-BuildGraph