from __future__ import annotations

import os
import re
import time
from pathlib import Path

from ueprojectbootstrap.context import BootstrapContext
from ueprojectbootstrap.steps.base import Step

_FILE_NAME_PATTERN = re.compile(r'<File\s+Name="([^"]*)"')
_EXCLUDED_NAME_PREFIXES = ("Templates/", "Samples/", "FeaturePacks/")
_REPLACE_ATTEMPTS = 5
_REPLACE_INITIAL_DELAY_SECONDS = 0.3


class UpdateDependenciesManifestStep(Step):
    order = 18

    def execute(self, context: BootstrapContext) -> None:
        if context.is_foreign_project:
            print("Skipping as the project is not native.")
            return

        manifest_path = context.repository_root / ".uedependencies"
        if not manifest_path.is_file():
            print(f"{manifest_path} not found. Skipping.")
            return

        # The manifest is machine-generated by GitDependencies with exactly one
        # self-closing <File Name="..." .../> element per line, so it's filtered as
        # plain text rather than re-serialized through an XML writer, to avoid
        # reformatting a file that can be tens of megabytes / hundreds of thousands
        # of lines.
        kept_lines: list[str] = []
        removed_count = 0

        with manifest_path.open("r", encoding="utf-8", newline="") as manifest_file:
            for line in manifest_file:
                match = _FILE_NAME_PATTERN.search(line)
                if match and match.group(1).startswith(_EXCLUDED_NAME_PREFIXES):
                    removed_count += 1
                    continue
                kept_lines.append(line)

        if removed_count == 0:
            print(f"No Templates/ or Samples/ entries found in {manifest_path}. Nothing to do.")
            return

        # Write to a sibling temp file and swap it in, instead of writing the
        # manifest in place: a file this large tends to get picked up by antivirus /
        # indexing right after being read, which can transiently deny write access to
        # the original path. The temp file is unaffected by that, and only the final
        # rename needs a short retry.
        temp_path = manifest_path.parent / f"{manifest_path.name}.tmp"
        try:
            with temp_path.open("w", encoding="utf-8", newline="") as manifest_file:
                manifest_file.writelines(kept_lines)

            self._replace_with_retry(temp_path, manifest_path)
        finally:
            temp_path.unlink(missing_ok=True)

        print(f"Removed {removed_count} Templates/Samples entries from {manifest_path}.")

    def _replace_with_retry(self, temp_path: Path, destination: Path) -> None:
        delay = _REPLACE_INITIAL_DELAY_SECONDS
        for attempt in range(1, _REPLACE_ATTEMPTS + 1):
            try:
                os.replace(temp_path, destination)
                return
            except PermissionError:
                if attempt == _REPLACE_ATTEMPTS:
                    raise
                print(f"{destination} is temporarily locked (attempt {attempt}/{_REPLACE_ATTEMPTS}). Retrying...")
                time.sleep(delay)
                delay *= 2
